Repository bvinca/battlesnake02, pull requests merged in 2025-06, with the labels that each got.

#58 test: add tests for hunt-smaller-snakes feature
  tests/hunt-smaller-snakes.test.js
Labels: test

#60 Feat: A star pathfinding
  CHANGELOG.md
  index.js
  src/a-star.js
Labels: feature

#69 chore: merge-release-branch-back-to-develop
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, release

#75 update deploy.yml
  .github/workflows/deploy.yml
Labels: fix

#76 Fix/update deploy
  .github/workflows/deploy.yml
Labels: bug

#81 update deploy.yml with the projectID
  .github/workflows/deploy.yml
Labels: bug

#82 Develop
  .github/workflows/deploy.yml
Labels: bug

#87 Fix/update package lock
  .editorconfig
  package-lock.json
Labels: fix

#88 Develop
  .editorconfig
  package-lock.json
Labels: fix
