Repository bvinca/battlesnake02, pull requests merged in 2025-05, with the labels that each got.

#37 Chore: Add user story and task templates
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user_story.md
  .gitignore
Labels: chore

#39 Feat: Allow-moving-into-other-snakes-tail-when-safe
  CHANGELOG.md
  index.js
  src/other-snakes-collision.js
  src/tail-collision.js
Labels: documentation, enhancement

#41 Hotfix/update snake appearance
  CHANGELOG.md
  index.js
Labels: documentation, hotfix

#42 Hotfix/update snake appearance
  CHANGELOG.md
  index.js
Labels: documentation, hotfix

#43 fix: update head-to-head collision logic
  src/head-to-head.js
Labels: fix

#47 Test/add coverage for core modules
  CHANGELOG.md
  tests/food-targeting.test.js
  tests/head-to-head.test.js
  tests/other-snakes-collision.test.js
  tests/self-collision.test.js
  tests/tail-collision.test.js
  tests/wall-collision.test.js
Labels: test

#50 feat: add flood fill algorithm for snake AI with TDD tests
  CHANGELOG.md
  jest.config.js
  package.json
  src/flood-fill.js
  tests/flood-fill.test.js
Labels: feature

#51 fix: update CHANGELOG.md
  CHANGELOG.md
Labels: fix

#53 Hotfix/fixing changelog.md
  CHANGELOG.md
Labels: hotfix
